version: '3'
services:

  identityms:
    build:
      context: ./identity_srv
      dockerfile: Dockerfile
    container_name: identityms
    ports:
      - "8080:8080"
    networks:
      - red_cn

  permissionsms:
    build:
      context: ./permissions_srv
      dockerfile: Dockerfile
    container_name: permissionsms
    ports:
      - "8082:8082"
    networks:
      - red_cn

  bffcloud:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: bffcloud
    ports:
      - "8089:8089"
    networks:
      - red_cn

  
networks:
  red_cn:
    driver: bridge